# Generated by Django 5.2 on 2025-11-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2024-2025', max_length=100)),
                ('semester', models.CharField(help_text='e.g., IV', max_length=10)),
                ('code', models.CharField(help_text='e.g., CS204', max_length=20)),
                ('course', models.CharField(help_text='e.g., COMPUTER ORGANIZATION', max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('grade', models.CharField(help_text='e.g., A+', max_length=5)),
                ('marks', models.CharField(blank=True, help_text='e.g., 95', max_length=10)),
                ('cgpa', models.CharField(blank=True, help_text='e.g., 9.5', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'code')},
            },
        ),
    ]
